WITH USER_FRIENDS_INVITED AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, TU.STATUS
FROM USERS U
INNER JOIN TRIPS_USERS TU
ON TU.USER_ID_REQUEST = 1000 /*Replace number with current users user id*/
WHERE TU.TRIP_ID = 1045 /*Replace number with trip id*/
),

USER_FRIENDS AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, 'Not Invited' as STATUS
FROM FRIENDS F, USERS U
WHERE
F.STATUS = 'Accepted' AND
((F.USER_ID1 = U.ID AND F.USER_ID2 = 1000) /*Replace number with current users user id*/
OR (F.USER_ID2 = U.ID AND F.USER_ID1 = 1000)) AND /*Replace number with current users user id*/
U.ID NOT IN (SELECT ID FROM USER_FRIENDS_INVITED)) 

SELECT * FROM USER_FRIENDS_INVITED
UNION
SELECT * FROM USER_FRIENDS
