SELECT DISTINCT TU.TRIP_ID, T.NAME, U.FIRST_NAME, U.ID, T.START_DATE, T.END_DATE, T.TRIP_TYPE
FROM TRIPS_USERS TU
INNER JOIN TRIPS T
ON T.ID = TU.TRIP_ID
INNER JOIN USERS U
ON TU.USER_ID_REQUEST = U.ID
WHERE TU.USER_ID = 1000 AND /*current user id*/
TU.STATUS = 'Pending'