/*for getting the photos like*/
WITH LIKE_COUNT AS (
SELECT PHOTO_ID, COUNT(*) AS LIKE_COUNT
FROM PHOTOS_LIKES
WHERE PHOTO_ID = 1000
GROUP BY PHOTO_ID),

STATUS AS (
SELECT PHOTO_ID, 'LIKED' AS STATUS
FROM PHOTOS_LIKES PL
WHERE PHOTO_ID = 1000 AND USER_ID = 1000),

PIC AS (
SELECT P.ID, P.URL
FROM PHOTOS P
WHERE P.ID = 1000 )

SELECT P.ID, P.URL, LC.LIKE_COUNT, S.STATUS
FROM PIC P
LEFT OUTER JOIN LIKE_COUNT LC
ON P.ID = LC.PHOTO_ID
LEFT OUTER JOIN STATUS S
ON LC.PHOTO_ID = S.PHOTO_ID;

/*for liking a photo
INSERT INTO PHOTOS_LIKES VALUES (1001, 1000)
*/
