SELECT PC.PHOTO_ID, U.FIRST_NAME, U.LAST_NAME, U.ID, PC.PHOTO_COMMENT, PC.COMMENT_DATE
FROM PHOTOS_COMMENTS PC
INNER JOIN USERS U
ON U.ID = PC.COMMENTER_ID
WHERE PC.PHOTO_ID = 1000
ORDER BY PC.COMMENT_DATE DESC