WITH USER_TRIP_TYPES AS (
SELECT DISTINCT T.TRIP_TYPE
FROM TRIPS_USERS TU
INNER JOIN TRIPS T
ON T.ID = TU.TRIP_ID
WHERE TU.USER_ID = 1000 /*current users id*/
)

/*PUBLIC_TRIPS_FOR_USERS_TRIP_TYPE AS (*/
SELECT DISTINCT T.ID, T.NAME, U.FIRST_NAME, T.TRIP_TYPE
FROM TRIPS T
INNER JOIN TRIPS_USERS TU
ON TU.TRIP_ID = T.ID
INNER JOIN USERS U
ON U.ID = T.OWNER
WHERE T.TRIP_TYPE IN
(SELECT TRIP_TYPE FROM USER_TRIP_TYPES)
AND T.PRIVACY = 1
AND TU.TRIP_ID NOT IN 
(SELECT TU.TRIP_ID 
FROM TRIPS_USERS TU
WHERE TU.USER_ID = 1000);

