/*
"WITH SEARCHED_USER AS ( \
SELECT U.ID \
FROM USERS U \
WHERE (U.EMAIL LIKE '%"+SEARCHED_STRING+"%' OR \
U.USERNAME LIKE '%"+SEARCHED_STRING+"%' OR \
U.FIRST_NAME LIKE '%"+SEARCHED_STRING+"%')),

CURRENT_USERS_FRIENDS AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, F.STATUS AS STATUS
FROM FRIENDS F, USERS U
INNER JOIN SEARCHED_USER SU
ON SU.ID = U.ID
WHERE (F.USER_ID1 = U.ID AND F.USER_ID2 = "+CURRENT_USER_ID+") 
OR (F.USER_ID2 = U.ID AND F.USER_ID1 = "+CURRENT_USER_ID+")), 

CURRENT_USERS_NON_FRIENDS AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, 'Not A Friend' AS STATUS
FROM SEARCHED_USER SU
INNER JOIN USERS U
ON SU.ID = U.ID
WHERE SU.ID NOT IN(
SELECT CUF.ID
FROM CURRENT_USERS_FRIENDS CUF
)
)
SELECT * FROM CURRENT_USERS_NON_FRIENDS
UNION
SELECT * FROM CURRENT_USERS_FRIENDS"*/

WITH SEARCHED_USER AS (
SELECT U.ID
FROM USERS U
WHERE (U.EMAIL LIKE '%rohit%' OR
U.USERNAME LIKE '%rohit%' OR
U.FIRST_NAME LIKE '%rohit%')),

CURRENT_USERS_FRIENDS AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, F.STATUS AS STATUS
FROM FRIENDS F, USERS U
INNER JOIN SEARCHED_USER SU
ON SU.ID = U.ID
WHERE (F.USER_ID1 = U.ID AND F.USER_ID2 = 1001) /*Replace number with current users user id*/
OR (F.USER_ID2 = U.ID AND F.USER_ID1 = 1001)), /*Replace number with current users user id*/

CURRENT_USERS_NON_FRIENDS AS (
SELECT U.ID, U.USERNAME, U.FIRST_NAME, U.EMAIL, 'Not A Friend' AS STATUS
FROM SEARCHED_USER SU
INNER JOIN USERS U
ON SU.ID = U.ID
WHERE SU.ID NOT IN(
SELECT CUF.ID
FROM CURRENT_USERS_FRIENDS CUF
)
)
SELECT * FROM CURRENT_USERS_NON_FRIENDS
UNION
SELECT * FROM CURRENT_USERS_FRIENDS