SELECT T.NAME AS Trip_Name, U.ID AS User_Id, U.FIRST_NAME AS Trip_Owner, T.START_DATE AS Start_Date, T.END_DATE AS End_Date, L.NAME AS Location
FROM TRIPS_LOCATIONS TL
INNER JOIN TRIPS T
ON T.ID = TL.TRIP_ID
INNER JOIN LOCATIONS L
ON L.ID = TL.LOCATION_ID
INNER JOIN USERS U
ON U.ID = T.OWNER
WHERE L.NAME LIKE '%San%' OR
T.NAME LIKE '%Goa%'