DROP TABLE USERS PURGE;	
DROP TABLE FRIENDS PURGE;	
DROP TABLE LOCATIONS PURGE;	
DROP TABLE VISITED_LOCATIONS PURGE;	
DROP TABLE DREAM_LOCATIONS PURGE;	
DROP TABLE TRIPS PURGE;	
DROP TABLE TRIPS_USERS PURGE;	
DROP TABLE TRIPS_LOCATIONS PURGE;	
DROP TABLE TRIPS_COMMENTS PURGE;	
DROP TABLE AFFILIATIONS PURGE;	
DROP TABLE AFFILIATED_TO PURGE;	
DROP TABLE ALBUMS PURGE;	
DROP TABLE PHOTOS PURGE;	
DROP TABLE VIDEOS PURGE;	
DROP TABLE PHOTOS_COMMENTS PURGE;	
DROP TABLE VIDEOS_COMMENTS PURGE;	

