WITH PICS AS (SELECT P.ID, P.LIKES, P.PIC_DATE, P.TAGLINE, P.URL, 'Photo' AS CONTENT_TYPE
FROM PHOTOS P
WHERE P.ALBUM_ID = 103
ORDER BY P.PIC_DATE DESC),
VIDS AS (
SELECT V.ID, V.LIKES, V.VIDEO_DATE, V.TAGLINE, V.URL, 'Video' AS CONTENT_TYPE
FROM VIDEOS V
WHERE V.ALBUM_ID = 103
ORDER BY V.VIDEO_DATE DESC
)

SELECT * FROM PICS UNION SELECT * FROM VIDS;