WITH TRIP_USERS AS 
(SELECT TU.USER_ID
FROM TRIPS_USERS TU
WHERE TU.USER_ID = '1')

SELECT T.ID, T.NAME, T.START_DATE
FROM TRIPS T
WHERE T.OWNER = '1'
UNION
SELECT T.ID, T.NAME, T.START_DATE
FROM TRIPS T
WHERE T.ID IN (SELECT * FROM TRIP_USERS)